theme: jekyll-theme-hacker
title: D.J. Novack
email: tuj66686@temple.edu
description: D.J. Novack is a PhD Student in the Voelz lab at Temple University. 
url: https://djnovack.github.io/
twitter_username: kpmans_theorem
github_username: DJNovack
# Dependencies
markdown: GFM
highlighter: pygments

plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - about.md
# Site settings
permalink: pretty

