theme: jekyll-theme-midnight
title: D.J. Novack
description: D.J. Novack is a PhD Student in the Voelz lab at Temple University. 
description: [About](https://djnovack.github.io/about)
# Site settings
permalink: pretty

# Pages permalink
defaults:
  -
    scope:
      type: "pages"
    values:
      permalink: /:path/:basename:output_ext
