# Setup
title:            D.J. Novack
logo:             images/signal-2020-07-05-115347.jpg
description:      D.J. Novack is a PhD Student in the Voelz lab at Temple University.
show_downloads:   false
url:              https://djnovack.github.io

author:
  name:           'D.J Novack'
  url:            https://twitter.com/kpmans_theorem
  

github:
  repo:           github.com/DJNovack/DJNovack.github.io
  
paginate:         50

# Custom vars
version:          1.0.0

# Dependencies
markdown: kramdown
kramdown:
  extensions: ["tables"]
highlighter: rouge


# Site settings
permalink: pretty

pages_list:       
  About: '/about'
  Research: '/research'
  Teaching: '/teaching'
  Publications/Presentations: '/pubs'
  Romashka: '/romashka'

gems:
  - jekyll-redirect-from
  - jekyll-paginate
  - jekyll-gallery-generator

plugins:
  - jekyll-gallery-generator

remote_theme: jirrian/jekyll-theme-image-grid@main
thumbsurl: "/thumbs"

gallery:
  dir: Romashka               # Path to the gallery
  symlink: false            # false: copy images into _site. true: create symbolic links (saves disk space)
  title: "Photos"           # Title for gallery index page
  title_prefix: "Photos: "  # Title prefix for gallery pages. Gallery title = title_prefix + gallery_name
  sort_field: "date_time"   # How to sort galleries on the index page.
                            # Possible values are: title, date_time, best_image
  thumbnail_size:
    x: 400                  # max width of thumbnails (in pixels)
    y: 400                  # max height of thumbnails (in pixels)
  # The following options are for individual galleries.
  galleries:
    Romashka:
