# Setup
title:            D.J. Novack
logo:             images/signal-2020-07-05-115347.jpg
description:      D.J. Novack is a PhD Student in the Voelz lab at Temple University.
show_downloads:   false
url:              https://djnovack.github.io

author:
  name:           'D.J Novack'
  url:            https://twitter.com/kpmans_theorem
  

github:
  repo:           github.com/DJNovack/DJNovack.github.io
  
paginate:         1

# Custom vars
version:          1.0.0

# Dependencies
markdown: kramdown
kramdown:
  extensions: ["tables"]
highlighter: true


# Site settings
permalink: pretty

pages_list:       
  About: '/about'

gems:
  - jekyll-redirect-from
  - jekyll-paginate

theme: jekyll-theme-minimal
