theme: jekyll-theme-midnight
title: D.J. Novack
description: D.J. Novack is a PhD Student in the Voelz lab at Temple University. They use molecular dynamics simulation to investigate biomolecular interections involved in disease. This site will allow you to keep up with their work.
